+default:
  access:
    site:
      login: true
    admin:
      login: true
      users:
        read: true
        list: true
  enabled: true
  readableName: Default
  description: 'Standard Benutzergruppe f√ºr alle Benutzer'
statistics:
  access:
    admin:
      statistics: true
  enabled: true
  readableName: 'Site Analyzer'
  description: 'Kann Statistiken der Seite einsehen'
editor:
  access:
    admin:
      cache: true
      pages:
        read: true
        update: true
        list: true
  readableName: 'Content Editor'
  description: 'Kann Seiten bearbeiten'
  enabled: true
pages:
  access:
    admin:
      cache: true
      pages: true
      flex-objects: true
  readableName: 'Site Editor'
  description: 'Kann Seiten verwalten'
  enabled: true
maintainer:
  access:
    admin:
      cache: true
      maintenance: true
      tools: true
      flex-objects: true
  enabled: true
  readableName: 'Site Maintainer'
  description: 'Kann die Seite warten/ in Stand halten'
settings:
  access:
    admin:
      configuration:
        system: true
        site: true
  readableName: Settings
  enabled: true
  description: 'Kann Seiten & Systemeinstellungen verwalten'
theme:
  access:
    admin:
      themes: true
  readableName: 'Theme Admin'
  enabled: true
  description: 'Kann Themes verwalten'
plugin:
  access:
    admin:
      plugins: true
  readableName: 'Plugins Admin'
  enabled: true
  description: 'Kann Plugins verwalten'
accounts:
  access:
    admin:
      users: true
  readableName: 'Account Manager'
  enabled: true
  description: 'Kann Benutzerkonten verwalten'
